In [1]:
from caffe2.python import workspace, model_helper
import numpy as np
# Create random tensor of three dimensions
x = np.random.rand(4, 3, 2)
print(x)
print(x.shape)

workspace.FeedBlob("my_x", x)

x2 = workspace.FetchBlob("my_x")
print(x2)


[[[0.41781277 0.1071414 ]
  [0.71337197 0.80591435]
  [0.58444634 0.17056359]]

 [[0.00743729 0.25614715]
  [0.12343792 0.74247775]
  [0.91767065 0.6639654 ]]

 [[0.26168192 0.48135076]
  [0.49295387 0.38500799]
  [0.63562422 0.81739623]]

 [[0.34761944 0.43999491]
  [0.47498028 0.64552865]
  [0.21607792 0.10009186]]]
(4, 3, 2)
[[[0.41781277 0.1071414 ]
  [0.71337197 0.80591435]
  [0.58444634 0.17056359]]

 [[0.00743729 0.25614715]
  [0.12343792 0.74247775]
  [0.91767065 0.6639654 ]]

 [[0.26168192 0.48135076]
  [0.49295387 0.38500799]
  [0.63562422 0.81739623]]

 [[0.34761944 0.43999491]
  [0.47498028 0.64552865]
  [0.21607792 0.10009186]]]


In [2]:
# Create the input data
data = np.random.rand(16, 100).astype(np.float32)

# Create labels for the data as integers [0, 9].
label = (np.random.rand(16) * 10).astype(np.int32)

workspace.FeedBlob("data", data)
workspace.FeedBlob("label", label)


True